/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Jesus And Sam
 * Created: Mar 18, 2018
 */

/* Drop statements */
/*DROP TABLE ORDERS;
DROP TABLE SEATS;
DROP TABLE CLIENTS;*/

/* Create table statements*/
CREATE TABLE SEATS (
    S_CAT VARCHAR(10) NOT NULL PRIMARY KEY,
    S_PRICE DOUBLE NOT NULL,
    S_SOLD NUMERIC(2) NOT NULL CHECK (S_SOLD BETWEEN 0 AND 75),
    S_TOTAL DOUBLE NOT NULL
);

CREATE TABLE CLIENTS (
    C_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    C_FNAME VARCHAR(40) NOT NULL,
    C_LNAME VARCHAR(40) NOT NULL,
    C_EMAIL VARCHAR(50) NOT NULL,
    C_ADDRESS VARCHAR(50) NOT NULL,
    C_ZIP VARCHAR(5) NOT NULL,
    C_CITY VARCHAR(50) NOT NULL,
    C_STATE VARCHAR(2) NOT NULL
);

CREATE TABLE ORDERS (
    O_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    O_QUANTITY NUMERIC(2) NOT NULL CHECK (O_QUANTITY BETWEEN 1 AND 75),
    O_SHIPPING DOUBLE NOT NULL,    
    O_FEE DOUBLE NOT NULL,
    O_TOTAL DOUBLE NOT NULL,
    O_CATNAME VARCHAR(10),
    C_ID INTEGER NOT NULL,
    FOREIGN KEY (C_ID) REFERENCES CLIENTS(C_ID) 
);

/* SEATS TABLE INFO */
INSERT INTO SEATS(S_CAT, S_PRICE, S_SOLD, S_TOTAL)
    VALUES('Category 1', 50, 0, 0);

INSERT INTO SEATS(S_CAT, S_PRICE, S_SOLD, S_TOTAL)
    VALUES('Category 2', 40, 0, 0);

INSERT INTO SEATS(S_CAT, S_PRICE, S_SOLD, S_TOTAL)
    VALUES('Category 3', 30, 0, 0);
