/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Jesus
 * Created: Feb 19, 2018
 */

/* Drop statements */
DROP TABLE ORDERS;
DROP TABLE SEATS;
DROP TABLE CLIENTS;

/* Create table statements*/
CREATE TABLE SEATS (
    S_CAT VARCHAR(10) NOT NULL PRIMARY KEY,
    S_PRICE DOUBLE NOT NULL,
    S_SOLD NUMERIC(2) CHECK (S_SOLD BETWEEN 1 AND 75),
    S_TOTAL DOUBLE
);

CREATE TABLE CLIENTS (
    C_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    C_FNAME VARCHAR(40) NOT NULL,
    C_LNAME VARCHAR(40) NOT NULL,
    C_EMAIL VARCHAR(50) NOT NULL,
    C_ADDRESS VARCHAR(50) NOT NULL,
    C_ZIP VARCHAR(5) NOT NULL,
    C_CITY VARCHAR(50) NOT NULL,
    C_STATE VARCHAR(2) NOT NULL
);

CREATE TABLE ORDERS (
    O_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    O_QUANTITY NUMERIC(2) CHECK (O_QUANTITY BETWEEN 1 AND 75),
    O_SHIPPING DOUBLE NOT NULL,    
    O_FEE DOUBLE NOT NULL,
    O_TOTAL DOUBLE NOT NULL,
    O_CATNAME VARCHAR(10),
    C_ID INTEGER,
    FOREIGN KEY (C_ID) REFERENCES CLIENTS(C_ID) 
);

/* SEATS TABLE INFO */
INSERT INTO SEATS(S_CAT, S_PRICE, S_SOLD, S_TOTAL)
    VALUES('Category 1', 50, null, null);

INSERT INTO SEATS(S_CAT, S_PRICE, S_SOLD, S_TOTAL)
    VALUES('Category 2', 40, null, null);

INSERT INTO SEATS(S_CAT, S_PRICE, S_SOLD, S_TOTAL)
    VALUES('Category 3', 30, null, null);


/* Random client info */
INSERT INTO CLIENTS( C_FNAME, C_LNAME, C_EMAIL, C_ADDRESS, C_ZIP, C_CITY, C_STATE)
    VALUES ('John', 'Doe', 'example@example.com', '902 Main St', '90210', 'Beverly Hills', 'CA');

INSERT INTO ORDERS(O_QUANTITY, O_SHIPPING, O_FEE, O_TOTAL, O_CATNAME, C_ID)
    VALUES (1, 5.95, 3.50, 53.50, 'Category 1', (SELECT MAX(C_ID) FROM CLIENTS));

UPDATE SEATS
    SET S_SOLD = 1, S_TOTAL = 53.50
    WHERE S_CAT = 'Category 1';

INSERT INTO CLIENTS( C_FNAME, C_LNAME, C_EMAIL, C_ADDRESS, C_ZIP, C_CITY, C_STATE)
    VALUES ('Lisa', 'Doe', 'example@example.com', '902 Main St', '90210', 'Beverly Hills', 'CA');

INSERT INTO ORDERS(O_QUANTITY, O_SHIPPING, O_FEE, O_TOTAL, O_CATNAME, C_ID)
    VALUES (1, 0, 2.80, 42.80, 'Category 2', (SELECT MAX(C_ID) FROM CLIENTS));

UPDATE SEATS
    SET S_SOLD = 1, S_TOTAL = 42.80
    WHERE S_CAT = 'Category 2';

INSERT INTO CLIENTS( C_FNAME, C_LNAME, C_EMAIL, C_ADDRESS, C_ZIP, C_CITY, C_STATE)
    VALUES ('Sam', 'Doe', 'example@example.com', '902 Main St', '90210', 'Beverly Hills', 'CA');

INSERT INTO ORDERS(O_QUANTITY, O_SHIPPING, O_FEE, O_TOTAL, O_CATNAME, C_ID)
    VALUES (1, 5.95, 2.10, 32.10, 'Category 3', (SELECT MAX(C_ID) FROM CLIENTS));

UPDATE SEATS
    SET S_SOLD = 1, S_TOTAL = 32.10
    WHERE S_CAT = 'Category 3';